//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BP.Auth.Web
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class PlantEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“PlantEntities”部分中的连接字符串初始化新 PlantEntities 对象。
        /// </summary>
        public PlantEntities() : base("name=PlantEntities", "PlantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PlantEntities 对象。
        /// </summary>
        public PlantEntities(string connectionString) : base(connectionString, "PlantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PlantEntities 对象。
        /// </summary>
        public PlantEntities(EntityConnection connection) : base(connection, "PlantEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Port_Dept> Port_Dept
        {
            get
            {
                if ((_Port_Dept == null))
                {
                    _Port_Dept = base.CreateObjectSet<Port_Dept>("Port_Dept");
                }
                return _Port_Dept;
            }
        }
        private ObjectSet<Port_Dept> _Port_Dept;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Port_Emp> Port_Emp
        {
            get
            {
                if ((_Port_Emp == null))
                {
                    _Port_Emp = base.CreateObjectSet<Port_Emp>("Port_Emp");
                }
                return _Port_Emp;
            }
        }
        private ObjectSet<Port_Emp> _Port_Emp;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Port_EmpDept> Port_EmpDept
        {
            get
            {
                if ((_Port_EmpDept == null))
                {
                    _Port_EmpDept = base.CreateObjectSet<Port_EmpDept>("Port_EmpDept");
                }
                return _Port_EmpDept;
            }
        }
        private ObjectSet<Port_EmpDept> _Port_EmpDept;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Port_EmpStation> Port_EmpStation
        {
            get
            {
                if ((_Port_EmpStation == null))
                {
                    _Port_EmpStation = base.CreateObjectSet<Port_EmpStation>("Port_EmpStation");
                }
                return _Port_EmpStation;
            }
        }
        private ObjectSet<Port_EmpStation> _Port_EmpStation;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Port_Station> Port_Station
        {
            get
            {
                if ((_Port_Station == null))
                {
                    _Port_Station = base.CreateObjectSet<Port_Station>("Port_Station");
                }
                return _Port_Station;
            }
        }
        private ObjectSet<Port_Station> _Port_Station;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Port_Dept EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPort_Dept(Port_Dept port_Dept)
        {
            base.AddObject("Port_Dept", port_Dept);
        }
    
        /// <summary>
        /// 用于向 Port_Emp EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPort_Emp(Port_Emp port_Emp)
        {
            base.AddObject("Port_Emp", port_Emp);
        }
    
        /// <summary>
        /// 用于向 Port_EmpDept EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPort_EmpDept(Port_EmpDept port_EmpDept)
        {
            base.AddObject("Port_EmpDept", port_EmpDept);
        }
    
        /// <summary>
        /// 用于向 Port_EmpStation EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPort_EmpStation(Port_EmpStation port_EmpStation)
        {
            base.AddObject("Port_EmpStation", port_EmpStation);
        }
    
        /// <summary>
        /// 用于向 Port_Station EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPort_Station(Port_Station port_Station)
        {
            base.AddObject("Port_Station", port_Station);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PlantModel", Name="Port_Dept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Port_Dept : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Port_Dept 对象。
        /// </summary>
        /// <param name="no">No 属性的初始值。</param>
        public static Port_Dept CreatePort_Dept(global::System.String no)
        {
            Port_Dept port_Dept = new Port_Dept();
            port_Dept.No = no;
            return port_Dept;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.String _No;
        partial void OnNoChanging(global::System.String value);
        partial void OnNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PlantModel", Name="Port_Emp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Port_Emp : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Port_Emp 对象。
        /// </summary>
        /// <param name="no">No 属性的初始值。</param>
        public static Port_Emp CreatePort_Emp(global::System.String no)
        {
            Port_Emp port_Emp = new Port_Emp();
            port_Emp.No = no;
            return port_Emp;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.String _No;
        partial void OnNoChanging(global::System.String value);
        partial void OnNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pass
        {
            get
            {
                return _Pass;
            }
            set
            {
                OnPassChanging(value);
                ReportPropertyChanging("Pass");
                _Pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pass");
                OnPassChanged();
            }
        }
        private global::System.String _Pass;
        partial void OnPassChanging(global::System.String value);
        partial void OnPassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FK_Dept
        {
            get
            {
                return _FK_Dept;
            }
            set
            {
                OnFK_DeptChanging(value);
                ReportPropertyChanging("FK_Dept");
                _FK_Dept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FK_Dept");
                OnFK_DeptChanged();
            }
        }
        private global::System.String _FK_Dept;
        partial void OnFK_DeptChanging(global::System.String value);
        partial void OnFK_DeptChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PlantModel", Name="Port_EmpDept")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Port_EmpDept : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Port_EmpDept 对象。
        /// </summary>
        /// <param name="fK_Emp">FK_Emp 属性的初始值。</param>
        /// <param name="fK_Dept">FK_Dept 属性的初始值。</param>
        public static Port_EmpDept CreatePort_EmpDept(global::System.String fK_Emp, global::System.String fK_Dept)
        {
            Port_EmpDept port_EmpDept = new Port_EmpDept();
            port_EmpDept.FK_Emp = fK_Emp;
            port_EmpDept.FK_Dept = fK_Dept;
            return port_EmpDept;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FK_Emp
        {
            get
            {
                return _FK_Emp;
            }
            set
            {
                if (_FK_Emp != value)
                {
                    OnFK_EmpChanging(value);
                    ReportPropertyChanging("FK_Emp");
                    _FK_Emp = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FK_Emp");
                    OnFK_EmpChanged();
                }
            }
        }
        private global::System.String _FK_Emp;
        partial void OnFK_EmpChanging(global::System.String value);
        partial void OnFK_EmpChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FK_Dept
        {
            get
            {
                return _FK_Dept;
            }
            set
            {
                if (_FK_Dept != value)
                {
                    OnFK_DeptChanging(value);
                    ReportPropertyChanging("FK_Dept");
                    _FK_Dept = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FK_Dept");
                    OnFK_DeptChanged();
                }
            }
        }
        private global::System.String _FK_Dept;
        partial void OnFK_DeptChanging(global::System.String value);
        partial void OnFK_DeptChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PlantModel", Name="Port_EmpStation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Port_EmpStation : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Port_EmpStation 对象。
        /// </summary>
        /// <param name="fK_Emp">FK_Emp 属性的初始值。</param>
        /// <param name="fK_Station">FK_Station 属性的初始值。</param>
        public static Port_EmpStation CreatePort_EmpStation(global::System.String fK_Emp, global::System.String fK_Station)
        {
            Port_EmpStation port_EmpStation = new Port_EmpStation();
            port_EmpStation.FK_Emp = fK_Emp;
            port_EmpStation.FK_Station = fK_Station;
            return port_EmpStation;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FK_Emp
        {
            get
            {
                return _FK_Emp;
            }
            set
            {
                if (_FK_Emp != value)
                {
                    OnFK_EmpChanging(value);
                    ReportPropertyChanging("FK_Emp");
                    _FK_Emp = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FK_Emp");
                    OnFK_EmpChanged();
                }
            }
        }
        private global::System.String _FK_Emp;
        partial void OnFK_EmpChanging(global::System.String value);
        partial void OnFK_EmpChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FK_Station
        {
            get
            {
                return _FK_Station;
            }
            set
            {
                if (_FK_Station != value)
                {
                    OnFK_StationChanging(value);
                    ReportPropertyChanging("FK_Station");
                    _FK_Station = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FK_Station");
                    OnFK_StationChanged();
                }
            }
        }
        private global::System.String _FK_Station;
        partial void OnFK_StationChanging(global::System.String value);
        partial void OnFK_StationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PlantModel", Name="Port_Station")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Port_Station : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Port_Station 对象。
        /// </summary>
        /// <param name="no">No 属性的初始值。</param>
        public static Port_Station CreatePort_Station(global::System.String no)
        {
            Port_Station port_Station = new Port_Station();
            port_Station.No = no;
            return port_Station;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.String _No;
        partial void OnNoChanging(global::System.String value);
        partial void OnNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StaGrade
        {
            get
            {
                return _StaGrade;
            }
            set
            {
                OnStaGradeChanging(value);
                ReportPropertyChanging("StaGrade");
                _StaGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StaGrade");
                OnStaGradeChanged();
            }
        }
        private Nullable<global::System.Int32> _StaGrade;
        partial void OnStaGradeChanging(Nullable<global::System.Int32> value);
        partial void OnStaGradeChanged();

        #endregion
    
    }

    #endregion
    
}
