//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WF.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Direction.
        /// </summary>
        public static string Button_AddDirection {
            get {
                return ResourceManager.GetString("Button_AddDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add FlowNode.
        /// </summary>
        public static string Button_AddFlowNode {
            get {
                return ResourceManager.GetString("Button_AddFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Label.
        /// </summary>
        public static string Button_AddLabel {
            get {
                return ResourceManager.GetString("Button_AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddTemplate.
        /// </summary>
        public static string Button_AddTemplate {
            get {
                return ResourceManager.GetString("Button_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Button_Cancle {
            get {
                return ResourceManager.GetString("Button_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Button_ClearContainer {
            get {
                return ResourceManager.GetString("Button_ClearContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePicture.
        /// </summary>
        public static string Button_CreatePicture {
            get {
                return ResourceManager.GetString("Button_CreatePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatTemplate.
        /// </summary>
        public static string Button_CreatTemplate {
            get {
                return ResourceManager.GetString("Button_CreatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_DelFlow {
            get {
                return ResourceManager.GetString("Button_DelFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesignerTable.
        /// </summary>
        public static string Button_DesignerTable {
            get {
                return ResourceManager.GetString("Button_DesignerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_ExportToXml {
            get {
                return ResourceManager.GetString("Button_ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowCheck.
        /// </summary>
        public static string Button_FlowCheck {
            get {
                return ResourceManager.GetString("Button_FlowCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowProper.
        /// </summary>
        public static string Button_FlowProper {
            get {
                return ResourceManager.GetString("Button_FlowProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowRptDefinition.
        /// </summary>
        public static string Button_FlowRptDefinition {
            get {
                return ResourceManager.GetString("Button_FlowRptDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_ImportFromXml {
            get {
                return ResourceManager.GetString("Button_ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFlow.
        /// </summary>
        public static string Button_NewFlow {
            get {
                return ResourceManager.GetString("Button_NewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Button_Previous {
            get {
                return ResourceManager.GetString("Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunFlow.
        /// </summary>
        public static string Button_RunFlow {
            get {
                return ResourceManager.GetString("Button_RunFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowLine.
        /// </summary>
        public static string Button_ShowLine {
            get {
                return ResourceManager.GetString("Button_ShowLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Button_Zoom {
            get {
                return ResourceManager.GetString("Button_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will delete Object,continue?.
        /// </summary>
        public static string Comfirm_Delete {
            get {
                return ResourceManager.GetString("Comfirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ContainerHeight {
            get {
                return ResourceManager.GetString("ContainerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ContainerWidth {
            get {
                return ResourceManager.GetString("ContainerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will delete WorkFlow,continue?.
        /// </summary>
        public static string DeleteFlow {
            get {
                return ResourceManager.GetString("DeleteFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will delete WorkFlow Sort,continue?.
        /// </summary>
        public static string DeleteFlowSort {
            get {
                return ResourceManager.GetString("DeleteFlowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditon.
        /// </summary>
        public static string DirectionCondition {
            get {
                return ResourceManager.GetString("DirectionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string DirectionLineType_Line {
            get {
                return ResourceManager.GetString("DirectionLineType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polyline.
        /// </summary>
        public static string DirectionLineType_Polyline {
            get {
                return ResourceManager.GetString("DirectionLineType_Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DirectionName {
            get {
                return ResourceManager.GetString("DirectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FlowNodeName {
            get {
                return ResourceManager.GetString("FlowNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FlowNodeType {
            get {
                return ResourceManager.GetString("FlowNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND_BRANCH.
        /// </summary>
        public static string FlowNodeType_AND_BRANCH {
            get {
                return ResourceManager.GetString("FlowNodeType_AND_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND_MERGE.
        /// </summary>
        public static string FlowNodeType_AND_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_AND_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATION.
        /// </summary>
        public static string FlowNodeType_AUTOMATION {
            get {
                return ResourceManager.GetString("FlowNodeType_AUTOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETION.
        /// </summary>
        public static string FlowNodeType_COMPLETION {
            get {
                return ResourceManager.GetString("FlowNodeType_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUMMY.
        /// </summary>
        public static string FlowNodeType_DUMMY {
            get {
                return ResourceManager.GetString("FlowNodeType_DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INITIAL.
        /// </summary>
        public static string FlowNodeType_INITIAL {
            get {
                return ResourceManager.GetString("FlowNodeType_INITIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERACTION.
        /// </summary>
        public static string FlowNodeType_INTERACTION {
            get {
                return ResourceManager.GetString("FlowNodeType_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR_BRANCH.
        /// </summary>
        public static string FlowNodeType_OR_BRANCH {
            get {
                return ResourceManager.GetString("FlowNodeType_OR_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR_MERGE.
        /// </summary>
        public static string FlowNodeType_OR_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_OR_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBPROCESS.
        /// </summary>
        public static string FlowNodeType_SUBPROCESS {
            get {
                return ResourceManager.GetString("FlowNodeType_SUBPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOTE_MERGE.
        /// </summary>
        public static string FlowNodeType_VOTE_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_VOTE_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Save ?.
        /// </summary>
        public static string IsSave {
            get {
                return ResourceManager.GetString("IsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignBottom.
        /// </summary>
        public static string Menu_AlignBottom {
            get {
                return ResourceManager.GetString("Menu_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignLeft.
        /// </summary>
        public static string Menu_AlignLeft {
            get {
                return ResourceManager.GetString("Menu_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignRight.
        /// </summary>
        public static string Menu_AlignRight {
            get {
                return ResourceManager.GetString("Menu_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlignTop.
        /// </summary>
        public static string Menu_AlignTop {
            get {
                return ResourceManager.GetString("Menu_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_CopyDirection {
            get {
                return ResourceManager.GetString("Menu_CopyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_CopyFlowNode {
            get {
                return ResourceManager.GetString("Menu_CopyFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_CopyLabel {
            get {
                return ResourceManager.GetString("Menu_CopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_CopySelected {
            get {
                return ResourceManager.GetString("Menu_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteDirection {
            get {
                return ResourceManager.GetString("Menu_DeleteDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteFlowNode {
            get {
                return ResourceManager.GetString("Menu_DeleteFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteLabel {
            get {
                return ResourceManager.GetString("Menu_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Menu_DeleteSelected {
            get {
                return ResourceManager.GetString("Menu_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Menu_ModifyDirection {
            get {
                return ResourceManager.GetString("Menu_ModifyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Menu_ModifyFlowNode {
            get {
                return ResourceManager.GetString("Menu_ModifyFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowGridLines.
        /// </summary>
        public static string Menu_ShowGridLines {
            get {
                return ResourceManager.GetString("Menu_ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin-activitity can not have pre-FlowNode..
        /// </summary>
        public static string Message_BeginActivitiesCanNotHavePreFlowNode {
            get {
                return ResourceManager.GetString("Message_BeginActivitiesCanNotHavePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin and end FlowNode  can not be the same..
        /// </summary>
        public static string Message_BeginAndEndFlowNodeCanNotBeTheSame {
            get {
                return ResourceManager.GetString("Message_BeginAndEndFlowNodeCanNotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branch-FlowNode only have one pre-FlowNode..
        /// </summary>
        public static string Message_BranchFlowNodeOnlyHaveOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_BranchFlowNodeOnlyHaveOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not have pre-FlowNode..
        /// </summary>
        public static string Message_CanNotHavePreFlowNode {
            get {
                return ResourceManager.GetString("Message_CanNotHavePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end-activitity can not have follow-up activitiy..
        /// </summary>
        public static string Message_EndFlowNodeCanNotHaveFollowUpActivitiy {
            get {
                return ResourceManager.GetString("Message_EndFlowNodeCanNotHaveFollowUpActivitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to merge-activitity  only have one follow-up activitiy..
        /// </summary>
        public static string Message_MergeFlowNodeOnlyHaveAFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MergeFlowNodeOnlyHaveAFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please modify workflow  in accordance with tips..
        /// </summary>
        public static string Message_ModifyWorkFlowByTip {
            get {
                return ResourceManager.GetString("Message_ModifyWorkFlowByTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule must be linked to begin-activitiy and end-FlowNode..
        /// </summary>
        public static string Message_MustBeLinkToBeginAndEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginAndEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule must be linked to begin-activitiy..
        /// </summary>
        public static string Message_MustBeLinkToBeginFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule must be linked to end-activitiy..
        /// </summary>
        public static string Message_MustBeLinkToEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have at least one end-FlowNode..
        /// </summary>
        public static string Message_MustHaveAtLeastOneEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have at least one follow-up FlowNode..
        /// </summary>
        public static string Message_MustHaveAtLeastOneFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have at least one pre-FlowNode..
        /// </summary>
        public static string Message_MustHaveAtLeastOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have only one begin-FlowNode..
        /// </summary>
        public static string Message_MustHaveOnlyOneBeginFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneBeginFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have only one follow-up FlowNode.
        /// </summary>
        public static string Message_MustHaveOnlyOneFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must have only one pre-FlowNode..
        /// </summary>
        public static string Message_MustHaveOnlyOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not have follow-up FlowNode..
        /// </summary>
        public static string Message_NotHaveFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_NotHaveFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to require the installation of pre-and follow-up activities..
        /// </summary>
        public static string Message_RequireTheInstallationOfPreAndFollowupFlowNode {
            get {
                return ResourceManager.GetString("Message_RequireTheInstallationOfPreAndFollowupFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkFlow had saved!.
        /// </summary>
        public static string Message_Saved {
            get {
                return ResourceManager.GetString("Message_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same rule that already exists..
        /// </summary>
        public static string Message_TheSameDirectionThatAlreadyExist {
            get {
                return ResourceManager.GetString("Message_TheSameDirectionThatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewDirection.
        /// </summary>
        public static string NewDirection {
            get {
                return ResourceManager.GetString("NewDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFlowNode.
        /// </summary>
        public static string NewFlowNode {
            get {
                return ResourceManager.GetString("NewFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFowSort.
        /// </summary>
        public static string NewFlowSort {
            get {
                return ResourceManager.GetString("NewFlowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewLabel.
        /// </summary>
        public static string NewLable {
            get {
                return ResourceManager.GetString("NewLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenFlow.
        /// </summary>
        public static string OpenFlow {
            get {
                return ResourceManager.GetString("OpenFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string RepeatDirection {
            get {
                return ResourceManager.GetString("RepeatDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string RepeatDirection_Horizontal {
            get {
                return ResourceManager.GetString("RepeatDirection_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string RepeatDirection_Vertical {
            get {
                return ResourceManager.GetString("RepeatDirection_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubFlow.
        /// </summary>
        public static string SubFlow {
            get {
                return ResourceManager.GetString("SubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept.
        /// </summary>
        public static string TbDept {
            get {
                return ResourceManager.GetString("TbDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string TbItemFlow {
            get {
                return ResourceManager.GetString("TbItemFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string TbStation {
            get {
                return ResourceManager.GetString("TbStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string UpdateLable {
            get {
                return ResourceManager.GetString("UpdateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string WorkFlowName {
            get {
                return ResourceManager.GetString("WorkFlowName", resourceCulture);
            }
        }
    }
}
