//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace Demo.BP.DA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BP.DA.DesignerSoap")]
    public interface DesignerSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EditLine", ReplyAction="*")]
        System.IAsyncResult BeginEditLine(Demo.BP.DA.EditLineRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.BP.DA.EditLineResponse EndEditLine(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EditLab", ReplyAction="*")]
        System.IAsyncResult BeginEditLab(Demo.BP.DA.EditLabRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.BP.DA.EditLabResponse EndEditLab(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EditMapAttr", ReplyAction="*")]
        System.IAsyncResult BeginEditMapAttr(Demo.BP.DA.EditMapAttrRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.BP.DA.EditMapAttrResponse EndEditMapAttr(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DelLine", ReplyAction="*")]
        System.IAsyncResult BeginDelLine(int oid, System.AsyncCallback callback, object asyncState);
        
        void EndDelLine(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DelLab", ReplyAction="*")]
        System.IAsyncResult BeginDelLab(int oid, System.AsyncCallback callback, object asyncState);
        
        void EndDelLab(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DelMapAttr", ReplyAction="*")]
        System.IAsyncResult BeginDelMapAttr(Demo.BP.DA.DelMapAttrRequest request, System.AsyncCallback callback, object asyncState);
        
        Demo.BP.DA.DelMapAttrResponse EndDelMapAttr(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditLineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditLine", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.EditLineRequestBody Body;
        
        public EditLineRequest() {
        }
        
        public EditLineRequest(Demo.BP.DA.EditLineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditLineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int oid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fk_mapdata;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int x1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int y1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int x2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int y2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int borderWidth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string borderColor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string borderStyle;
        
        public EditLineRequestBody() {
        }
        
        public EditLineRequestBody(int oid, string fk_mapdata, int x1, int y1, int x2, int y2, int borderWidth, string borderColor, string borderStyle) {
            this.oid = oid;
            this.fk_mapdata = fk_mapdata;
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
            this.borderWidth = borderWidth;
            this.borderColor = borderColor;
            this.borderStyle = borderStyle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditLineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditLineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.EditLineResponseBody Body;
        
        public EditLineResponse() {
        }
        
        public EditLineResponse(Demo.BP.DA.EditLineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditLineResponseBody {
        
        public EditLineResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditLabRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditLab", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.EditLabRequestBody Body;
        
        public EditLabRequest() {
        }
        
        public EditLabRequest(Demo.BP.DA.EditLabRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditLabRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int oid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fk_mapdata;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int y;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string frontColor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string frontName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string frontWeight;
        
        public EditLabRequestBody() {
        }
        
        public EditLabRequestBody(int oid, string fk_mapdata, int x, int y, string frontColor, string frontName, string frontWeight) {
            this.oid = oid;
            this.fk_mapdata = fk_mapdata;
            this.x = x;
            this.y = y;
            this.frontColor = frontColor;
            this.frontName = frontName;
            this.frontWeight = frontWeight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditLabResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditLabResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.EditLabResponseBody Body;
        
        public EditLabResponse() {
        }
        
        public EditLabResponse(Demo.BP.DA.EditLabResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditLabResponseBody {
        
        public EditLabResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMapAttrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMapAttr", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.EditMapAttrRequestBody Body;
        
        public EditMapAttrRequest() {
        }
        
        public EditMapAttrRequest(Demo.BP.DA.EditMapAttrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditMapAttrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mypk;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int x;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int y;
        
        public EditMapAttrRequestBody() {
        }
        
        public EditMapAttrRequestBody(string mypk, int x, int y) {
            this.mypk = mypk;
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMapAttrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMapAttrResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.EditMapAttrResponseBody Body;
        
        public EditMapAttrResponse() {
        }
        
        public EditMapAttrResponse(Demo.BP.DA.EditMapAttrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditMapAttrResponseBody {
        
        public EditMapAttrResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelMapAttrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelMapAttr", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.DelMapAttrRequestBody Body;
        
        public DelMapAttrRequest() {
        }
        
        public DelMapAttrRequest(Demo.BP.DA.DelMapAttrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelMapAttrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mypk;
        
        public DelMapAttrRequestBody() {
        }
        
        public DelMapAttrRequestBody(string mypk) {
            this.mypk = mypk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelMapAttrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelMapAttrResponse", Namespace="http://tempuri.org/", Order=0)]
        public Demo.BP.DA.DelMapAttrResponseBody Body;
        
        public DelMapAttrResponse() {
        }
        
        public DelMapAttrResponse(Demo.BP.DA.DelMapAttrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DelMapAttrResponseBody {
        
        public DelMapAttrResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DesignerSoapChannel : Demo.BP.DA.DesignerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DesignerSoapClient : System.ServiceModel.ClientBase<Demo.BP.DA.DesignerSoap>, Demo.BP.DA.DesignerSoap {
        
        private BeginOperationDelegate onBeginEditLineDelegate;
        
        private EndOperationDelegate onEndEditLineDelegate;
        
        private System.Threading.SendOrPostCallback onEditLineCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditLabDelegate;
        
        private EndOperationDelegate onEndEditLabDelegate;
        
        private System.Threading.SendOrPostCallback onEditLabCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditMapAttrDelegate;
        
        private EndOperationDelegate onEndEditMapAttrDelegate;
        
        private System.Threading.SendOrPostCallback onEditMapAttrCompletedDelegate;
        
        private BeginOperationDelegate onBeginDelLineDelegate;
        
        private EndOperationDelegate onEndDelLineDelegate;
        
        private System.Threading.SendOrPostCallback onDelLineCompletedDelegate;
        
        private BeginOperationDelegate onBeginDelLabDelegate;
        
        private EndOperationDelegate onEndDelLabDelegate;
        
        private System.Threading.SendOrPostCallback onDelLabCompletedDelegate;
        
        private BeginOperationDelegate onBeginDelMapAttrDelegate;
        
        private EndOperationDelegate onEndDelMapAttrDelegate;
        
        private System.Threading.SendOrPostCallback onDelMapAttrCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DesignerSoapClient() {
        }
        
        public DesignerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DesignerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesignerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesignerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditLineCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditLabCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditMapAttrCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DelLineCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DelLabCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DelMapAttrCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.BP.DA.DesignerSoap.BeginEditLine(Demo.BP.DA.EditLineRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditLine(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginEditLine(int oid, string fk_mapdata, int x1, int y1, int x2, int y2, int borderWidth, string borderColor, string borderStyle, System.AsyncCallback callback, object asyncState) {
            Demo.BP.DA.EditLineRequest inValue = new Demo.BP.DA.EditLineRequest();
            inValue.Body = new Demo.BP.DA.EditLineRequestBody();
            inValue.Body.oid = oid;
            inValue.Body.fk_mapdata = fk_mapdata;
            inValue.Body.x1 = x1;
            inValue.Body.y1 = y1;
            inValue.Body.x2 = x2;
            inValue.Body.y2 = y2;
            inValue.Body.borderWidth = borderWidth;
            inValue.Body.borderColor = borderColor;
            inValue.Body.borderStyle = borderStyle;
            return ((Demo.BP.DA.DesignerSoap)(this)).BeginEditLine(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.BP.DA.EditLineResponse Demo.BP.DA.DesignerSoap.EndEditLine(System.IAsyncResult result) {
            return base.Channel.EndEditLine(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndEditLine(System.IAsyncResult result) {
            Demo.BP.DA.EditLineResponse retVal = ((Demo.BP.DA.DesignerSoap)(this)).EndEditLine(result);
        }
        
        private System.IAsyncResult OnBeginEditLine(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int oid = ((int)(inValues[0]));
            string fk_mapdata = ((string)(inValues[1]));
            int x1 = ((int)(inValues[2]));
            int y1 = ((int)(inValues[3]));
            int x2 = ((int)(inValues[4]));
            int y2 = ((int)(inValues[5]));
            int borderWidth = ((int)(inValues[6]));
            string borderColor = ((string)(inValues[7]));
            string borderStyle = ((string)(inValues[8]));
            return this.BeginEditLine(oid, fk_mapdata, x1, y1, x2, y2, borderWidth, borderColor, borderStyle, callback, asyncState);
        }
        
        private object[] OnEndEditLine(System.IAsyncResult result) {
            this.EndEditLine(result);
            return null;
        }
        
        private void OnEditLineCompleted(object state) {
            if ((this.EditLineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditLineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditLineAsync(int oid, string fk_mapdata, int x1, int y1, int x2, int y2, int borderWidth, string borderColor, string borderStyle) {
            this.EditLineAsync(oid, fk_mapdata, x1, y1, x2, y2, borderWidth, borderColor, borderStyle, null);
        }
        
        public void EditLineAsync(int oid, string fk_mapdata, int x1, int y1, int x2, int y2, int borderWidth, string borderColor, string borderStyle, object userState) {
            if ((this.onBeginEditLineDelegate == null)) {
                this.onBeginEditLineDelegate = new BeginOperationDelegate(this.OnBeginEditLine);
            }
            if ((this.onEndEditLineDelegate == null)) {
                this.onEndEditLineDelegate = new EndOperationDelegate(this.OnEndEditLine);
            }
            if ((this.onEditLineCompletedDelegate == null)) {
                this.onEditLineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditLineCompleted);
            }
            base.InvokeAsync(this.onBeginEditLineDelegate, new object[] {
                        oid,
                        fk_mapdata,
                        x1,
                        y1,
                        x2,
                        y2,
                        borderWidth,
                        borderColor,
                        borderStyle}, this.onEndEditLineDelegate, this.onEditLineCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.BP.DA.DesignerSoap.BeginEditLab(Demo.BP.DA.EditLabRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditLab(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginEditLab(int oid, string fk_mapdata, int x, int y, string frontColor, string frontName, string frontWeight, System.AsyncCallback callback, object asyncState) {
            Demo.BP.DA.EditLabRequest inValue = new Demo.BP.DA.EditLabRequest();
            inValue.Body = new Demo.BP.DA.EditLabRequestBody();
            inValue.Body.oid = oid;
            inValue.Body.fk_mapdata = fk_mapdata;
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.frontColor = frontColor;
            inValue.Body.frontName = frontName;
            inValue.Body.frontWeight = frontWeight;
            return ((Demo.BP.DA.DesignerSoap)(this)).BeginEditLab(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.BP.DA.EditLabResponse Demo.BP.DA.DesignerSoap.EndEditLab(System.IAsyncResult result) {
            return base.Channel.EndEditLab(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndEditLab(System.IAsyncResult result) {
            Demo.BP.DA.EditLabResponse retVal = ((Demo.BP.DA.DesignerSoap)(this)).EndEditLab(result);
        }
        
        private System.IAsyncResult OnBeginEditLab(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int oid = ((int)(inValues[0]));
            string fk_mapdata = ((string)(inValues[1]));
            int x = ((int)(inValues[2]));
            int y = ((int)(inValues[3]));
            string frontColor = ((string)(inValues[4]));
            string frontName = ((string)(inValues[5]));
            string frontWeight = ((string)(inValues[6]));
            return this.BeginEditLab(oid, fk_mapdata, x, y, frontColor, frontName, frontWeight, callback, asyncState);
        }
        
        private object[] OnEndEditLab(System.IAsyncResult result) {
            this.EndEditLab(result);
            return null;
        }
        
        private void OnEditLabCompleted(object state) {
            if ((this.EditLabCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditLabCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditLabAsync(int oid, string fk_mapdata, int x, int y, string frontColor, string frontName, string frontWeight) {
            this.EditLabAsync(oid, fk_mapdata, x, y, frontColor, frontName, frontWeight, null);
        }
        
        public void EditLabAsync(int oid, string fk_mapdata, int x, int y, string frontColor, string frontName, string frontWeight, object userState) {
            if ((this.onBeginEditLabDelegate == null)) {
                this.onBeginEditLabDelegate = new BeginOperationDelegate(this.OnBeginEditLab);
            }
            if ((this.onEndEditLabDelegate == null)) {
                this.onEndEditLabDelegate = new EndOperationDelegate(this.OnEndEditLab);
            }
            if ((this.onEditLabCompletedDelegate == null)) {
                this.onEditLabCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditLabCompleted);
            }
            base.InvokeAsync(this.onBeginEditLabDelegate, new object[] {
                        oid,
                        fk_mapdata,
                        x,
                        y,
                        frontColor,
                        frontName,
                        frontWeight}, this.onEndEditLabDelegate, this.onEditLabCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.BP.DA.DesignerSoap.BeginEditMapAttr(Demo.BP.DA.EditMapAttrRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditMapAttr(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginEditMapAttr(string mypk, int x, int y, System.AsyncCallback callback, object asyncState) {
            Demo.BP.DA.EditMapAttrRequest inValue = new Demo.BP.DA.EditMapAttrRequest();
            inValue.Body = new Demo.BP.DA.EditMapAttrRequestBody();
            inValue.Body.mypk = mypk;
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((Demo.BP.DA.DesignerSoap)(this)).BeginEditMapAttr(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.BP.DA.EditMapAttrResponse Demo.BP.DA.DesignerSoap.EndEditMapAttr(System.IAsyncResult result) {
            return base.Channel.EndEditMapAttr(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndEditMapAttr(System.IAsyncResult result) {
            Demo.BP.DA.EditMapAttrResponse retVal = ((Demo.BP.DA.DesignerSoap)(this)).EndEditMapAttr(result);
        }
        
        private System.IAsyncResult OnBeginEditMapAttr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string mypk = ((string)(inValues[0]));
            int x = ((int)(inValues[1]));
            int y = ((int)(inValues[2]));
            return this.BeginEditMapAttr(mypk, x, y, callback, asyncState);
        }
        
        private object[] OnEndEditMapAttr(System.IAsyncResult result) {
            this.EndEditMapAttr(result);
            return null;
        }
        
        private void OnEditMapAttrCompleted(object state) {
            if ((this.EditMapAttrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditMapAttrCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditMapAttrAsync(string mypk, int x, int y) {
            this.EditMapAttrAsync(mypk, x, y, null);
        }
        
        public void EditMapAttrAsync(string mypk, int x, int y, object userState) {
            if ((this.onBeginEditMapAttrDelegate == null)) {
                this.onBeginEditMapAttrDelegate = new BeginOperationDelegate(this.OnBeginEditMapAttr);
            }
            if ((this.onEndEditMapAttrDelegate == null)) {
                this.onEndEditMapAttrDelegate = new EndOperationDelegate(this.OnEndEditMapAttr);
            }
            if ((this.onEditMapAttrCompletedDelegate == null)) {
                this.onEditMapAttrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditMapAttrCompleted);
            }
            base.InvokeAsync(this.onBeginEditMapAttrDelegate, new object[] {
                        mypk,
                        x,
                        y}, this.onEndEditMapAttrDelegate, this.onEditMapAttrCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.BP.DA.DesignerSoap.BeginDelLine(int oid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelLine(oid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Demo.BP.DA.DesignerSoap.EndDelLine(System.IAsyncResult result) {
            base.Channel.EndDelLine(result);
        }
        
        private System.IAsyncResult OnBeginDelLine(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int oid = ((int)(inValues[0]));
            return ((Demo.BP.DA.DesignerSoap)(this)).BeginDelLine(oid, callback, asyncState);
        }
        
        private object[] OnEndDelLine(System.IAsyncResult result) {
            ((Demo.BP.DA.DesignerSoap)(this)).EndDelLine(result);
            return null;
        }
        
        private void OnDelLineCompleted(object state) {
            if ((this.DelLineCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DelLineCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DelLineAsync(int oid) {
            this.DelLineAsync(oid, null);
        }
        
        public void DelLineAsync(int oid, object userState) {
            if ((this.onBeginDelLineDelegate == null)) {
                this.onBeginDelLineDelegate = new BeginOperationDelegate(this.OnBeginDelLine);
            }
            if ((this.onEndDelLineDelegate == null)) {
                this.onEndDelLineDelegate = new EndOperationDelegate(this.OnEndDelLine);
            }
            if ((this.onDelLineCompletedDelegate == null)) {
                this.onDelLineCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDelLineCompleted);
            }
            base.InvokeAsync(this.onBeginDelLineDelegate, new object[] {
                        oid}, this.onEndDelLineDelegate, this.onDelLineCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.BP.DA.DesignerSoap.BeginDelLab(int oid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelLab(oid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Demo.BP.DA.DesignerSoap.EndDelLab(System.IAsyncResult result) {
            base.Channel.EndDelLab(result);
        }
        
        private System.IAsyncResult OnBeginDelLab(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int oid = ((int)(inValues[0]));
            return ((Demo.BP.DA.DesignerSoap)(this)).BeginDelLab(oid, callback, asyncState);
        }
        
        private object[] OnEndDelLab(System.IAsyncResult result) {
            ((Demo.BP.DA.DesignerSoap)(this)).EndDelLab(result);
            return null;
        }
        
        private void OnDelLabCompleted(object state) {
            if ((this.DelLabCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DelLabCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DelLabAsync(int oid) {
            this.DelLabAsync(oid, null);
        }
        
        public void DelLabAsync(int oid, object userState) {
            if ((this.onBeginDelLabDelegate == null)) {
                this.onBeginDelLabDelegate = new BeginOperationDelegate(this.OnBeginDelLab);
            }
            if ((this.onEndDelLabDelegate == null)) {
                this.onEndDelLabDelegate = new EndOperationDelegate(this.OnEndDelLab);
            }
            if ((this.onDelLabCompletedDelegate == null)) {
                this.onDelLabCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDelLabCompleted);
            }
            base.InvokeAsync(this.onBeginDelLabDelegate, new object[] {
                        oid}, this.onEndDelLabDelegate, this.onDelLabCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Demo.BP.DA.DesignerSoap.BeginDelMapAttr(Demo.BP.DA.DelMapAttrRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelMapAttr(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDelMapAttr(string mypk, System.AsyncCallback callback, object asyncState) {
            Demo.BP.DA.DelMapAttrRequest inValue = new Demo.BP.DA.DelMapAttrRequest();
            inValue.Body = new Demo.BP.DA.DelMapAttrRequestBody();
            inValue.Body.mypk = mypk;
            return ((Demo.BP.DA.DesignerSoap)(this)).BeginDelMapAttr(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Demo.BP.DA.DelMapAttrResponse Demo.BP.DA.DesignerSoap.EndDelMapAttr(System.IAsyncResult result) {
            return base.Channel.EndDelMapAttr(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndDelMapAttr(System.IAsyncResult result) {
            Demo.BP.DA.DelMapAttrResponse retVal = ((Demo.BP.DA.DesignerSoap)(this)).EndDelMapAttr(result);
        }
        
        private System.IAsyncResult OnBeginDelMapAttr(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string mypk = ((string)(inValues[0]));
            return this.BeginDelMapAttr(mypk, callback, asyncState);
        }
        
        private object[] OnEndDelMapAttr(System.IAsyncResult result) {
            this.EndDelMapAttr(result);
            return null;
        }
        
        private void OnDelMapAttrCompleted(object state) {
            if ((this.DelMapAttrCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DelMapAttrCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DelMapAttrAsync(string mypk) {
            this.DelMapAttrAsync(mypk, null);
        }
        
        public void DelMapAttrAsync(string mypk, object userState) {
            if ((this.onBeginDelMapAttrDelegate == null)) {
                this.onBeginDelMapAttrDelegate = new BeginOperationDelegate(this.OnBeginDelMapAttr);
            }
            if ((this.onEndDelMapAttrDelegate == null)) {
                this.onEndDelMapAttrDelegate = new EndOperationDelegate(this.OnEndDelMapAttr);
            }
            if ((this.onDelMapAttrCompletedDelegate == null)) {
                this.onDelMapAttrCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDelMapAttrCompleted);
            }
            base.InvokeAsync(this.onBeginDelMapAttrDelegate, new object[] {
                        mypk}, this.onEndDelMapAttrDelegate, this.onDelMapAttrCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Demo.BP.DA.DesignerSoap CreateChannel() {
            return new DesignerSoapClientChannel(this);
        }
        
        private class DesignerSoapClientChannel : ChannelBase<Demo.BP.DA.DesignerSoap>, Demo.BP.DA.DesignerSoap {
            
            public DesignerSoapClientChannel(System.ServiceModel.ClientBase<Demo.BP.DA.DesignerSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginEditLine(Demo.BP.DA.EditLineRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("EditLine", _args, callback, asyncState);
                return _result;
            }
            
            public Demo.BP.DA.EditLineResponse EndEditLine(System.IAsyncResult result) {
                object[] _args = new object[0];
                Demo.BP.DA.EditLineResponse _result = ((Demo.BP.DA.EditLineResponse)(base.EndInvoke("EditLine", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEditLab(Demo.BP.DA.EditLabRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("EditLab", _args, callback, asyncState);
                return _result;
            }
            
            public Demo.BP.DA.EditLabResponse EndEditLab(System.IAsyncResult result) {
                object[] _args = new object[0];
                Demo.BP.DA.EditLabResponse _result = ((Demo.BP.DA.EditLabResponse)(base.EndInvoke("EditLab", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEditMapAttr(Demo.BP.DA.EditMapAttrRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("EditMapAttr", _args, callback, asyncState);
                return _result;
            }
            
            public Demo.BP.DA.EditMapAttrResponse EndEditMapAttr(System.IAsyncResult result) {
                object[] _args = new object[0];
                Demo.BP.DA.EditMapAttrResponse _result = ((Demo.BP.DA.EditMapAttrResponse)(base.EndInvoke("EditMapAttr", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelLine(int oid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oid;
                System.IAsyncResult _result = base.BeginInvoke("DelLine", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDelLine(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DelLine", _args, result);
            }
            
            public System.IAsyncResult BeginDelLab(int oid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = oid;
                System.IAsyncResult _result = base.BeginInvoke("DelLab", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDelLab(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DelLab", _args, result);
            }
            
            public System.IAsyncResult BeginDelMapAttr(Demo.BP.DA.DelMapAttrRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("DelMapAttr", _args, callback, asyncState);
                return _result;
            }
            
            public Demo.BP.DA.DelMapAttrResponse EndDelMapAttr(System.IAsyncResult result) {
                object[] _args = new object[0];
                Demo.BP.DA.DelMapAttrResponse _result = ((Demo.BP.DA.DelMapAttrResponse)(base.EndInvoke("DelMapAttr", _args, result)));
                return _result;
            }
        }
    }
}
