//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace FreeFrm.FF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FF.FreeFrmSoap")]
    public interface FreeFrmSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState);
        
        string EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/RunSQLs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRunSQLs(string sqls, System.AsyncCallback callback, object asyncState);
        
        int EndRunSQLs(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/RunSQLReturnTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRunSQLReturnTable(string sql, System.AsyncCallback callback, object asyncState);
        
        string EndRunSQLReturnTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/RequestSFTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginRequestSFTable(string ensName, System.AsyncCallback callback, object asyncState);
        
        string EndRequestSFTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GenerFrm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGenerFrm(string fk_mapdata, System.AsyncCallback callback, object asyncState);
        
        string EndGenerFrm(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SaveFrm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginSaveFrm(string xml, string sqls, System.AsyncCallback callback, object asyncState);
        
        string EndSaveFrm(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FreeFrmSoapChannel : FreeFrm.FF.FreeFrmSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RunSQLsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RunSQLsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RunSQLReturnTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RunSQLReturnTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestSFTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RequestSFTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerFrmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GenerFrmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveFrmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveFrmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FreeFrmSoapClient : System.ServiceModel.ClientBase<FreeFrm.FF.FreeFrmSoap>, FreeFrm.FF.FreeFrmSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginRunSQLsDelegate;
        
        private EndOperationDelegate onEndRunSQLsDelegate;
        
        private System.Threading.SendOrPostCallback onRunSQLsCompletedDelegate;
        
        private BeginOperationDelegate onBeginRunSQLReturnTableDelegate;
        
        private EndOperationDelegate onEndRunSQLReturnTableDelegate;
        
        private System.Threading.SendOrPostCallback onRunSQLReturnTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginRequestSFTableDelegate;
        
        private EndOperationDelegate onEndRequestSFTableDelegate;
        
        private System.Threading.SendOrPostCallback onRequestSFTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginGenerFrmDelegate;
        
        private EndOperationDelegate onEndGenerFrmDelegate;
        
        private System.Threading.SendOrPostCallback onGenerFrmCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveFrmDelegate;
        
        private EndOperationDelegate onEndSaveFrmDelegate;
        
        private System.Threading.SendOrPostCallback onSaveFrmCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FreeFrmSoapClient() {
        }
        
        public FreeFrmSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FreeFrmSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreeFrmSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FreeFrmSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<RunSQLsCompletedEventArgs> RunSQLsCompleted;
        
        public event System.EventHandler<RunSQLReturnTableCompletedEventArgs> RunSQLReturnTableCompleted;
        
        public event System.EventHandler<RequestSFTableCompletedEventArgs> RequestSFTableCompleted;
        
        public event System.EventHandler<GenerFrmCompletedEventArgs> GenerFrmCompleted;
        
        public event System.EventHandler<SaveFrmCompletedEventArgs> SaveFrmCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FreeFrm.FF.FreeFrmSoap.BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FreeFrm.FF.FreeFrmSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((FreeFrm.FF.FreeFrmSoap)(this)).BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = ((FreeFrm.FF.FreeFrmSoap)(this)).EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FreeFrm.FF.FreeFrmSoap.BeginRunSQLs(string sqls, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRunSQLs(sqls, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int FreeFrm.FF.FreeFrmSoap.EndRunSQLs(System.IAsyncResult result) {
            return base.Channel.EndRunSQLs(result);
        }
        
        private System.IAsyncResult OnBeginRunSQLs(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sqls = ((string)(inValues[0]));
            return ((FreeFrm.FF.FreeFrmSoap)(this)).BeginRunSQLs(sqls, callback, asyncState);
        }
        
        private object[] OnEndRunSQLs(System.IAsyncResult result) {
            int retVal = ((FreeFrm.FF.FreeFrmSoap)(this)).EndRunSQLs(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRunSQLsCompleted(object state) {
            if ((this.RunSQLsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RunSQLsCompleted(this, new RunSQLsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RunSQLsAsync(string sqls) {
            this.RunSQLsAsync(sqls, null);
        }
        
        public void RunSQLsAsync(string sqls, object userState) {
            if ((this.onBeginRunSQLsDelegate == null)) {
                this.onBeginRunSQLsDelegate = new BeginOperationDelegate(this.OnBeginRunSQLs);
            }
            if ((this.onEndRunSQLsDelegate == null)) {
                this.onEndRunSQLsDelegate = new EndOperationDelegate(this.OnEndRunSQLs);
            }
            if ((this.onRunSQLsCompletedDelegate == null)) {
                this.onRunSQLsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRunSQLsCompleted);
            }
            base.InvokeAsync(this.onBeginRunSQLsDelegate, new object[] {
                        sqls}, this.onEndRunSQLsDelegate, this.onRunSQLsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FreeFrm.FF.FreeFrmSoap.BeginRunSQLReturnTable(string sql, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRunSQLReturnTable(sql, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FreeFrm.FF.FreeFrmSoap.EndRunSQLReturnTable(System.IAsyncResult result) {
            return base.Channel.EndRunSQLReturnTable(result);
        }
        
        private System.IAsyncResult OnBeginRunSQLReturnTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sql = ((string)(inValues[0]));
            return ((FreeFrm.FF.FreeFrmSoap)(this)).BeginRunSQLReturnTable(sql, callback, asyncState);
        }
        
        private object[] OnEndRunSQLReturnTable(System.IAsyncResult result) {
            string retVal = ((FreeFrm.FF.FreeFrmSoap)(this)).EndRunSQLReturnTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRunSQLReturnTableCompleted(object state) {
            if ((this.RunSQLReturnTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RunSQLReturnTableCompleted(this, new RunSQLReturnTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RunSQLReturnTableAsync(string sql) {
            this.RunSQLReturnTableAsync(sql, null);
        }
        
        public void RunSQLReturnTableAsync(string sql, object userState) {
            if ((this.onBeginRunSQLReturnTableDelegate == null)) {
                this.onBeginRunSQLReturnTableDelegate = new BeginOperationDelegate(this.OnBeginRunSQLReturnTable);
            }
            if ((this.onEndRunSQLReturnTableDelegate == null)) {
                this.onEndRunSQLReturnTableDelegate = new EndOperationDelegate(this.OnEndRunSQLReturnTable);
            }
            if ((this.onRunSQLReturnTableCompletedDelegate == null)) {
                this.onRunSQLReturnTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRunSQLReturnTableCompleted);
            }
            base.InvokeAsync(this.onBeginRunSQLReturnTableDelegate, new object[] {
                        sql}, this.onEndRunSQLReturnTableDelegate, this.onRunSQLReturnTableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FreeFrm.FF.FreeFrmSoap.BeginRequestSFTable(string ensName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRequestSFTable(ensName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FreeFrm.FF.FreeFrmSoap.EndRequestSFTable(System.IAsyncResult result) {
            return base.Channel.EndRequestSFTable(result);
        }
        
        private System.IAsyncResult OnBeginRequestSFTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string ensName = ((string)(inValues[0]));
            return ((FreeFrm.FF.FreeFrmSoap)(this)).BeginRequestSFTable(ensName, callback, asyncState);
        }
        
        private object[] OnEndRequestSFTable(System.IAsyncResult result) {
            string retVal = ((FreeFrm.FF.FreeFrmSoap)(this)).EndRequestSFTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRequestSFTableCompleted(object state) {
            if ((this.RequestSFTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RequestSFTableCompleted(this, new RequestSFTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RequestSFTableAsync(string ensName) {
            this.RequestSFTableAsync(ensName, null);
        }
        
        public void RequestSFTableAsync(string ensName, object userState) {
            if ((this.onBeginRequestSFTableDelegate == null)) {
                this.onBeginRequestSFTableDelegate = new BeginOperationDelegate(this.OnBeginRequestSFTable);
            }
            if ((this.onEndRequestSFTableDelegate == null)) {
                this.onEndRequestSFTableDelegate = new EndOperationDelegate(this.OnEndRequestSFTable);
            }
            if ((this.onRequestSFTableCompletedDelegate == null)) {
                this.onRequestSFTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRequestSFTableCompleted);
            }
            base.InvokeAsync(this.onBeginRequestSFTableDelegate, new object[] {
                        ensName}, this.onEndRequestSFTableDelegate, this.onRequestSFTableCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FreeFrm.FF.FreeFrmSoap.BeginGenerFrm(string fk_mapdata, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGenerFrm(fk_mapdata, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FreeFrm.FF.FreeFrmSoap.EndGenerFrm(System.IAsyncResult result) {
            return base.Channel.EndGenerFrm(result);
        }
        
        private System.IAsyncResult OnBeginGenerFrm(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fk_mapdata = ((string)(inValues[0]));
            return ((FreeFrm.FF.FreeFrmSoap)(this)).BeginGenerFrm(fk_mapdata, callback, asyncState);
        }
        
        private object[] OnEndGenerFrm(System.IAsyncResult result) {
            string retVal = ((FreeFrm.FF.FreeFrmSoap)(this)).EndGenerFrm(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGenerFrmCompleted(object state) {
            if ((this.GenerFrmCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GenerFrmCompleted(this, new GenerFrmCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GenerFrmAsync(string fk_mapdata) {
            this.GenerFrmAsync(fk_mapdata, null);
        }
        
        public void GenerFrmAsync(string fk_mapdata, object userState) {
            if ((this.onBeginGenerFrmDelegate == null)) {
                this.onBeginGenerFrmDelegate = new BeginOperationDelegate(this.OnBeginGenerFrm);
            }
            if ((this.onEndGenerFrmDelegate == null)) {
                this.onEndGenerFrmDelegate = new EndOperationDelegate(this.OnEndGenerFrm);
            }
            if ((this.onGenerFrmCompletedDelegate == null)) {
                this.onGenerFrmCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGenerFrmCompleted);
            }
            base.InvokeAsync(this.onBeginGenerFrmDelegate, new object[] {
                        fk_mapdata}, this.onEndGenerFrmDelegate, this.onGenerFrmCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FreeFrm.FF.FreeFrmSoap.BeginSaveFrm(string xml, string sqls, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveFrm(xml, sqls, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string FreeFrm.FF.FreeFrmSoap.EndSaveFrm(System.IAsyncResult result) {
            return base.Channel.EndSaveFrm(result);
        }
        
        private System.IAsyncResult OnBeginSaveFrm(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string xml = ((string)(inValues[0]));
            string sqls = ((string)(inValues[1]));
            return ((FreeFrm.FF.FreeFrmSoap)(this)).BeginSaveFrm(xml, sqls, callback, asyncState);
        }
        
        private object[] OnEndSaveFrm(System.IAsyncResult result) {
            string retVal = ((FreeFrm.FF.FreeFrmSoap)(this)).EndSaveFrm(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveFrmCompleted(object state) {
            if ((this.SaveFrmCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveFrmCompleted(this, new SaveFrmCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveFrmAsync(string xml, string sqls) {
            this.SaveFrmAsync(xml, sqls, null);
        }
        
        public void SaveFrmAsync(string xml, string sqls, object userState) {
            if ((this.onBeginSaveFrmDelegate == null)) {
                this.onBeginSaveFrmDelegate = new BeginOperationDelegate(this.OnBeginSaveFrm);
            }
            if ((this.onEndSaveFrmDelegate == null)) {
                this.onEndSaveFrmDelegate = new EndOperationDelegate(this.OnEndSaveFrm);
            }
            if ((this.onSaveFrmCompletedDelegate == null)) {
                this.onSaveFrmCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveFrmCompleted);
            }
            base.InvokeAsync(this.onBeginSaveFrmDelegate, new object[] {
                        xml,
                        sqls}, this.onEndSaveFrmDelegate, this.onSaveFrmCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FreeFrm.FF.FreeFrmSoap CreateChannel() {
            return new FreeFrmSoapClientChannel(this);
        }
        
        private class FreeFrmSoapClientChannel : ChannelBase<FreeFrm.FF.FreeFrmSoap>, FreeFrm.FF.FreeFrmSoap {
            
            public FreeFrmSoapClientChannel(System.ServiceModel.ClientBase<FreeFrm.FF.FreeFrmSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public string EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRunSQLs(string sqls, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = sqls;
                System.IAsyncResult _result = base.BeginInvoke("RunSQLs", _args, callback, asyncState);
                return _result;
            }
            
            public int EndRunSQLs(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("RunSQLs", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRunSQLReturnTable(string sql, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = sql;
                System.IAsyncResult _result = base.BeginInvoke("RunSQLReturnTable", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRunSQLReturnTable(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RunSQLReturnTable", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRequestSFTable(string ensName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = ensName;
                System.IAsyncResult _result = base.BeginInvoke("RequestSFTable", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRequestSFTable(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RequestSFTable", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGenerFrm(string fk_mapdata, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = fk_mapdata;
                System.IAsyncResult _result = base.BeginInvoke("GenerFrm", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGenerFrm(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GenerFrm", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveFrm(string xml, string sqls, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = xml;
                _args[1] = sqls;
                System.IAsyncResult _result = base.BeginInvoke("SaveFrm", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSaveFrm(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SaveFrm", _args, result)));
                return _result;
            }
        }
    }
}
