<script src="../../Comm/Scripts/jquery-1.6.2.min.js" type="text/javascript"></script>
<script src="../../Comm/Scripts/miniui/miniui.js" type="text/javascript"></script>
<link href="../Style/control.css" rel="stylesheet" type="text/css" />
<link href="../Style/demo.css" rel="stylesheet" type="text/css" />
<link href="../../Comm/Scripts/miniui/themes/default/miniui.css" rel="stylesheet"
    type="text/css" />
